CREATE TABLE [dbo].[Dzien](
	[Id] INT IDENTITY(1,1) NOT NULL,
	[DzienTygodnia] NVARCHAR (200) NOT NULL,
	CONSTRAINT [PK_Dzien] PRIMARY KEY CLUSTERED ([Id] ASC)
);

CREATE TABLE [dbo].[Plan](
	[Id] INT IDENTITY(1, 1) NOT NULL,
	[Nazwa] NVARCHAR (200) NOT NULL
	CONSTRAINT [PK_Plan] PRIMARY KEY CLUSTERED ([Id] ASC)
);

CREATE TABLE [dbo].[Przedmiot](
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Godzina] NVARCHAR (200) NOT NULL,
	[Nazwa] NVARCHAR (200) NOT NULL,
	[DzienId] INT NOT NULL,
	[PlanId] INT NOT NULL,
	CONSTRAINT [PK_Przedmiot] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_Przedmiot_Dzien] FOREIGN KEY ([DzienId]) 
		REFERENCES [dbo].[Dzien] ([Id]) ON DELETE CASCADE,
	CONSTRAINT [FK_Przedmiot_Plan] FOREIGN KEY ([PlanId]) 
		REFERENCES [dbo].[Plan] ([Id]) ON DELETE CASCADE
);