//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plan_lekcji.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Godzina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Godzina()
        {
            this.Przedmiot = new HashSet<Przedmiot>();
        }
    
        public int Id { get; set; }
        public string Godzina1 { get; set; }
        public int PlanId { get; set; }
    
        public virtual Plan Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Przedmiot> Przedmiot { get; set; }
    }
}
