//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Plan_lekcji.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przedmiot
    {
        public int Id { get; set; }
        public string Godzina { get; set; }
        public string Nazwa { get; set; }
        public int DzienId { get; set; }
        [Required]
        public int PlanId { get; set; }
    
        public virtual Dzien Dzien { get; set; }
        public virtual Plan Plan { get; set; }
    }
}
